sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g standard
  - npm i -g mocha
install:
  - travis_retry npm install
  - apt -t trusty-backports install lxd
  - apt -y install lxd
script:
  - npm run test