matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "7"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt -t trusty-backports install lxd
  - lxc list
  - npm i -g standard
  - npm i -g mocha
install:
  - travis_retry npm install
script:
  - npm run test