language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt -t trusty-backports install lxd
  - sudo apt -y install lxd
  - lxc list
  - npm i -g standard
  - npm i -g mocha
install:
  - travis_retry npm install
script:
  - npm run test