site_name: LXC Query
site_description: 'A Node.js LXD client which uses your local instance of LXD and `lxc query` to manage your local or remote LXD servers.'
site_author: 'Lawrence Cherone'
site_url: 'https://github.com/lcherone/lxc-query'

# Copyright
copyright: 'Copyright &copy; 2018 Lawrence Cherone'

# Theme
theme:
  #feature:
  #  tabs: true
  logo: 
    icon: 'language'
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
    
# Configuration
repo_name: 'lcherone/lxc-query'
repo_url: 'https://github.com/lcherone/lxc-query'
edit_uri: ''

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/lcherone/lxc-query'
  disqus: 'lxc-query'
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
 
# Pages
pages:
    - Home: index.md
    - Server: server.md
    - Certificates: certificates.md
    - Containers: containers.md
    - Snapshots: snapshots.md
    - Images: images.md
    - Aliases: aliases.md
    - Profiles: profiles.md
    - Networks: networks.md
    - Files: files.md
    - Logs: logs.md
    - Metadata: metadata.md
    - Operations: operations.md
