site_name: LXC Query
theme: readthedocs
pages:
    - Home: index.md
    - Server: server.md
    - Certificates: certificates.md
    - Containers: containers.md
    - Snapshots: snapshots.md
    - Images: images.md
    - Aliases: aliases.md
    - Profiles: profiles.md
    - Networks: networks.md
    - Files: files.md
    - Logs: logs.md
    - Metadata: metadata.md
    
